### ISSUE TITLE
Can't download patched rom

### ISSUE THREAD

**Issue by sanbor** [xeinherjar/nixel#1]
When clicking "Patch ROM" I get the error:

```
TypeError: Cannot read property 'length' of undefined
    at patchChr (main.js:375)
    at ChildScope.$scope.patchROM (main.js:307)
    at $parseFunctionCall (vendor.js:12345)
    at callback (vendor.js:21438)
    at ChildScope.$eval (vendor.js:14401)
    at ChildScope.$apply (vendor.js:14500)
    at HTMLDivElement.<anonymous> (vendor.js:21443)
    at HTMLDivElement.eventHandler (vendor.js:3014)
(anonymous) @ vendor.js:11607
(anonymous) @ vendor.js:8557
$apply @ vendor.js:14502
(anonymous) @ vendor.js:21443
eventHandler @ vendor.js:3014
```

I tried some roms from https://learn.adafruit.com/how-to-hack-roms-to-add-your-own-sprites/roms-to-try

**Comment by xeinherjar** [comment]
Oh man I don't even know if this thing can even build now.

I just tested, and can confirm that the error appears, that said, if you make an edit it does work after that.  So load a rom, make a modification, then click patch.

If it still fails let me know and I'll see if I can't modernize it or at least get it to build

**Comment by ghost** [comment]
Still doesn't work.

**Comment by xeinherjar** [comment]
Hey @twtg93 Like I posted above, you have to make a modification before hitting `patch` for it to work.
The UI is not clear on how this work, sorry for that. (this was project for a code school forever ago)

Once you have a ROM loaded you need to click on either `0, 1, 2, 3`, this corresponds to the palette look up value that will be used.  Then click on the editor, patch should work after that.
![nixel-ss](https://user-images.githubusercontent.com/1631523/115913438-99c9d100-a43e-11eb-8109-79dd6a521950.png)

**Comment by ghost** [comment]
I did it. Such an awesome patcher! :)
